### ISSUE TITLE
Add rp2040 to supported architectures

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-Debug#32]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: Bug Report

in library.properties.
Generates warning when compiling recent cyphal projects.

**Comment by aentinger** [comment]
Are you sure you are using the latest released version (1.1.5)? I fixed such a bug in #31 .

**Comment by generationmake** [comment]
please check [library.properties](https://github.com/107-systems/107-Arduino-Debug/blob/main/library.properties) line 9

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave: here you go ... https://github.com/107-systems/107-Arduino-Debug/releases/tag/1.1.6 -
